version: '3.3'

services:
  web:
    build: ./project
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8004
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8004