version: '3'

services:

  fast_api:
    build:
      context: ./fastAPI
    ports:
      - "8000:8000"
    depends_on:
      - react_ui

  react_ui:
    build:
      context: ./reactUI
    ports:
      - "3000:3000"
    depends_on:
      - fast_api
