export const routes = [
  {
    name: 'Home',
    path: '/home',
    key: 'name',
    footer: false,
    header: true,
    profile: false,
    protected: true,
    isAdminPage: true,
  },
  {
    name: 'About us',
    path: '/aboutus',
    key: 'aboutUs',
    footer: true,
    header: true,
    profile: false,
    protected: false,
  },
  {
    name: 'Students',
    path: '/student',
    key: 'students',
    footer: false,
    header: false,
    profile: false,
    protected: true,
    isAdminPage: true,
  },
  {
    name: 'Contact',
    path: '/contact',
    key: 'contact',
    footer: true,
    header: true,
    profile: false,
    protected: false,
  },
  {
    name: 'Blog',
    path: '/blog',
    key: 'blog',
    footer: true,
    header: true,
    profile: false,
    protected: false,
  },
  {
    name: 'Dashboard',
    path: '/dashboard',
    key: 'dashboard',
    footer: false,
    header: true,
    profile: true,
    protected: true,
  },
  {
    name: 'Logout',
    path: '/logout',
    key: 'logout',
    footer: false,
    header: false,
    profile: true,
    protected: true,
  },
  {
    name: 'Colleges',
    path: '/colleges',
    key: 'colleges',
    footer: false,
    header: true,
    profile: false,
    protected: true,
  },
  {
    name: 'College',
    path: '/colleges/add',
    key: 'college',
    footer: false,
    header: true,
    profile: false,
    protected: true,
    isAdminPage: true,
  },
  {
    name: 'Application',
    path: '/application',
    key: 'application',
    footer: false,
    header: true,
    profile: false,
    protected: true,
  },
  {
    name: 'Visa',
    path: '/visa',
    key: 'visa',
    footer: false,
    header: true,
    profile: false,
    protected: true,
  },
  {
    name: 'My Account',
    path: '/account',
    key: 'account',
    footer: false,
    header: false,
    profile: true,
    protected: true,
  },
  {
    name: 'Settings',
    path: '/settings',
    key: 'settings',
    footer: false,
    header: false,
    profile: true,
    protected: true,
  },
];
